repos:
  - repo: local
    hooks:
      - id: cargo-check
        name: cargo check
        description: Check the package for errors
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-fmt
        name: cargo fmt
        description: Format Rust code
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        description: Lint Rust code
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo test
        description: Run tests
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false